[package]
name = "medtrack"
version = "0.0.1"
edition = "2024"  # <--- THÊM DÒNG NÀY ĐỂ DÙNG CÚ PHÁP MỚI

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
medtrack = "0x0"